#!/bin/sh -ue

# This script deploys a master or release version.
#
# See [README.md] for an explanation of this and how CI should use it.
version=${1:-master}

# Use implicit version when master, if we can..
if [ "${version}" = "master" ]; then
  version=$(sed -En 's/.*<version>(.*)<\/version>.*/\1/p' pom.xml| head -1)
fi

build-bin/maven/maven_deploy -pl -:brave-bom
# Deploy the Bill of Materials (BOM) separately as it is unhooked from the main project intentionally
build-bin/maven/maven_deploy -f brave-bom/pom.xml

# openzipkin/brave publishes Javadoc to gh-pages (https://zipkin.io/brave/) on release
case ${version} in
  *-SNAPSHOT )
    ;;
  * )
    build-bin/javadoc_to_gh_pages ${version}
    ;;
esac
