#!/bin/sh -ue

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.

# We avoid -T1C because some plugins don't work in parallel and also ITs are
# difficult to debug when failures are in parallel.
./mvnw verify -nsu "$@"
