#!/bin/sh
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

set -ue

# This script prepares GPG, needed to sign jars for Sonatype deployment during `maven_deploy`

# ensure GPG commands work non-interactively
export GPG_TTY=$(tty)
# import signing key used for jar files
echo ${GPG_SIGNING_KEY} | base64 --decode | gpg --batch --passphrase ${GPG_PASSPHRASE} --import
