package com.github.kristofa.brave.grpc;

import static org.hamcrest.core.Is.is;
import static org.hamcrest.core.IsEqual.equalTo;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

import com.github.kristofa.brave.Brave;
import com.github.kristofa.brave.LocalTracer;
import com.github.kristofa.brave.Sampler;
import com.github.kristofa.brave.SpanId;
import com.google.common.util.concurrent.ListenableFuture;
import com.twitter.zipkin.gen.Annotation;
import com.twitter.zipkin.gen.BinaryAnnotation;
import com.twitter.zipkin.gen.Span;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.ServerInterceptors;
import io.grpc.Status;
import io.grpc.examples.helloworld.GreeterGrpc;
import io.grpc.examples.helloworld.GreeterGrpc.GreeterBlockingStub;
import io.grpc.examples.helloworld.GreeterGrpc.GreeterFutureStub;
import io.grpc.examples.helloworld.HelloReply;
import io.grpc.examples.helloworld.HelloRequest;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.net.ServerSocket;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Optional;

public class BraveGrpcInterceptorsTest {

    private static final HelloRequest HELLO_REQUEST = HelloRequest.newBuilder()
        .setName("brave")
        .build();

    private Server server;
    private ManagedChannel channel;
    private Brave brave;
    private boolean enableSampling;

    @Before
    public void before() throws Exception {
        enableSampling = true;
        SpanCollectorForTesting.getInstance().getCollectedSpans().clear();

        final Brave.Builder builder = new Brave.Builder();
        brave = builder
            .spanCollector(SpanCollectorForTesting.getInstance())
            .traceSampler(new ExplicitSampler())
            .build();

        int serverPort = pickUnusedPort();
        server = ServerBuilder.forPort(serverPort)
            .addService(ServerInterceptors.intercept(
                GreeterGrpc.bindService(new GreeterImpl()), new BraveGrpcServerInterceptor(brave)))
            .build()
            .start();

        channel = ManagedChannelBuilder.forAddress("localhost", serverPort)
            .intercept(new BraveGrpcClientInterceptor("helloWorldCaller", brave))
            .usePlaintext(true)
            .build();
    }

    @Test
    public void testBlockingUnaryCall() throws Exception {
        GreeterBlockingStub stub = GreeterGrpc.newBlockingStub(channel);
        HelloReply reply = stub.sayHello(HELLO_REQUEST);
        assertThat(reply.getMessage(), is("Hello brave"));
        validateSpans();
    }

    @Test
    public void testAsyncUnaryCall() throws Exception {
        GreeterFutureStub futureStub = GreeterGrpc.newFutureStub(channel);
        ListenableFuture<HelloReply> helloReplyListenableFuture = futureStub.sayHello(HELLO_REQUEST);
        HelloReply reply = helloReplyListenableFuture.get();
        assertThat(reply.getMessage(), is("Hello brave"));
        validateSpans();
    }

    @Test
    public void usesExistingTraceId() throws Exception {
        LocalTracer localTracer = brave.localTracer();
        SpanId spanId = localTracer.startNewSpan("localSpan", "myop");
        GreeterBlockingStub stub = GreeterGrpc.newBlockingStub(channel);
        //This call will be made using hte context of the localTracer as it's parent
        HelloReply reply = stub.sayHello(HELLO_REQUEST);
        assertThat(reply.getMessage(), is("Hello brave"));
        validateSpans();
        List<Span> spans = SpanCollectorForTesting.getInstance().getCollectedSpans();
        Optional<Span> maybeSpan = spans.stream()
            .filter(s -> s.getAnnotations().stream().anyMatch(a -> "ss".equals(a.value)))
            .findFirst();
        assertTrue("Could not find expected server span", maybeSpan.isPresent());
        Span span = maybeSpan.get();
        //Verify that the localTracer's trace id and span id were propagated to the server
        assertThat(span.getTrace_id(), is(equalTo(spanId.getTraceId())));
        assertThat(span.getParent_id(), is(equalTo(spanId.getSpanId())));
    }

    /**
     * This test verifies that the sampling rate determined by the client is correctly propagated to the server.
     * Since sampling is disabled in by the client, then there should be no span generated by the server.
     */
    @Test
    public void noSamplesWhenSamplingDisabled() throws Exception {
        enableSampling = false;
        GreeterBlockingStub stub = GreeterGrpc.newBlockingStub(channel);
        HelloReply reply = stub.sayHello(HELLO_REQUEST);
        assertThat(reply.getMessage(), is("Hello brave"));
        List<Span> spans = SpanCollectorForTesting.getInstance().getCollectedSpans();
        assertThat(spans.size(), is(equalTo(0)));
    }

    /**
     * Validating that two spans were generated indicates that a span was generated by both the
     * server and the client.
     */
    private void validateSpans() throws Exception {
        List<Span> spans = SpanCollectorForTesting.getInstance().getCollectedSpans();
        assertThat(spans.size(), is(equalTo(2)));
        assertThat(spans.get(0).getTrace_id(), is(equalTo(spans.get(1).getTrace_id())));
        validateServerSpan(spans.get(0));
        validateClientSpan(spans.get(1));
    }

    private void validateClientSpan(Span span) {
        assertThat(span.getName(), is(equalTo("helloworld.greeter/sayhello")));
        List<BinaryAnnotation> binaryAnnotations = span.getBinary_annotations();
        assertThat(binaryAnnotations.size(), is(equalTo(2)));
        assertBinaryAnnotation(binaryAnnotations.get(0), "http.uri", "helloworld.greeter/sayhello");
        assertBinaryAnnotation(binaryAnnotations.get(1), "http.responsecode", String.valueOf(Status.OK.getCode().value()));
        assertAnnotation("cs", span.getAnnotations());
        assertAnnotation("cr", span.getAnnotations());
    }

    private void validateServerSpan(Span span) {
        assertThat(span.getName(), is(equalTo("helloworld.greeter/sayhello")));
        List<BinaryAnnotation> binaryAnnotations = span.getBinary_annotations();
        assertThat(binaryAnnotations.size(), is(equalTo(1)));
        assertBinaryAnnotation(binaryAnnotations.get(0), "http.responsecode", String.valueOf(Status.OK.getCode().value()));
        assertAnnotation("ss", span.getAnnotations());
        assertAnnotation("sr", span.getAnnotations());
    }

    private void assertAnnotation(String annotationName, List<Annotation> annotations) {
        Optional<Annotation> annotation = annotations.stream().filter(a -> annotationName.equals(a.value)).findFirst();
        assertTrue("Could not find annotation: " + annotationName, annotation.isPresent());
    }

    private void assertBinaryAnnotation(BinaryAnnotation binaryAnnotation, String key, String value) {
        assertThat(binaryAnnotation.getKey(), is(equalTo(key)));
        assertThat(new String(binaryAnnotation.getValue(), StandardCharsets.UTF_8), is(equalTo(value)));
    }

    @After
    public void tearDown() {
        channel.shutdownNow();
        server.shutdownNow();
    }

    public static int pickUnusedPort() {
        try {
            ServerSocket serverSocket = new ServerSocket(0);
            int port = serverSocket.getLocalPort();
            serverSocket.close();
            return port;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private class ExplicitSampler extends Sampler {

        @Override
        public boolean isSampled(long traceId) {
            return enableSampling;
        }
    }
}
